languageCode = "en-us"
title = "Yuvi Panda"
baseurl = "http://words.yuvi.in/"
theme = "hyde"
author = "Yuvi Panda"

[params]
description = "Open Knowledge | Open Source | Jupyter | Kubernetes | Wikimedia | Python"
colorscheme = "white"
copyright = "CC0"

[[menu.main]]
name = 'twitter'
url = 'https://twitter.com/yuvipanda'

[[menu.main]]
name = 'github'
url = 'https://github.com/yuvipanda'

[[menu.main]]
name = 'email'
url = 'mailto:yuvipanda@gmail.com'
[social]
twitter = "yuvipanda"
github = "yuvipanda"
