languageCode: "en-us"
title: "Yuvi Panda"
baseurl: "http://words.yuvi.in/"
theme: "hugo-theme-bootstrap4-blog"
author: "Yuvi Panda"
Paginate: 10

params:
    description: "[JupyterHub](https://github.com/jupyterhub/jupyterhub) | [MyBinder](https://mybinder.org) | [Kubernetes](https://k8s.io) | Open Culture"
    navbarDisabled: true
    colorscheme: "white"
    copyright: "CC0"
    iconFont: "font-awesome"
    truncate: false
    profileImage: /profile.jpg

    sidebar:
        items:
            - title: about
              content: |
                I build infrastructure that helps reduce accidental complexities when using code to solve problems.
            - title: projects
              content: |
                  Primarily working on [Zero to JupyterHub](https://z2jh.jupyter.org) and [MyBinder](https://mybinder.org)

                  See more on my [GitHub Profile](https://github.com/yuvipanda)
            - title: work
              content: |
                  I design, build & operate large scale teaching infrastructure for the [Data Science Division at UC Berkeley](https://data.berkeley.edu/).

                  I also help run [MyBinder](https://mybinder.org) thanks to a generous grant from the Gordon & Betty Moore Foundation.
            - title: contact
              content: |
                [Email](mailto:yuvipanda@gmail.com) is the best way to contact me privately.
                [Twitter](https://twitter.com/yuvipanda) is the best way to contact me publicly.
